### ISSUE TITLE
Hébergement du site

### ISSUE THREAD

**Issue by aeschbacher** [aeschbacher/pcsmonr#1]
Avec l'hébergeur actuel (https://ouvaton.coop/):
- Il n' y a pas d'accès SSH
- Les temps de réponses sont excessivement lents

TODO:
- évaluer et sélectionner d'autres possibilités d'hébergement
- écrire un court mémo à Luciano + Arsène expliquant les raisons pour lesquelles ce changement est souhaitable

Par exemple:
https://www.ovh.com/fr/hebergement-web/hebergement-pro.xml

**Comment by cneuen** [comment]
Il existe des hébergeurs spécialisés WordPress comme https://wordpress.com ou https://wpengine.com/ mais je pense qu'un hébergeur généraliste est préférable pour garder une latitude plus large sur l'utilisation de notre plateforme.

Au niveau des généralistes, OVH me semble la meilleure option.
https://www.ovh.com/fr/hebergement-web/hebergement-pro.xml

**Les arguments les plus positifs :** 

- Accès SSH
- Backup automatiques (J-1 à J-14)
- SSL Let's Encrypt compris dans l'offre
- Installation de WordPress intégrée sous forme de module

**Par contre :** 

- Prix plus elevé : 

7,19 € / mois = **86,28 € TTC / an**
(Ouvaton = 40 € TTC / an mais attention, dépassements sur 2016 = 50 € à priori)

**Comment by aeschbacher** [comment]
Changement d'hébergement validé => closing
