### ISSUE TITLE
Administration des DNS

### ISSUE THREAD

**Issue by cneuen** [aeschbacher/pcsmonr#10]
Le registrar des 2 domaines est OVH : 

**Domain Name: PETITS-CHANTEURS-STRASBOURG.COM**
   Registrar: OVH
   Sponsoring Registrar IANA ID: 433
   Whois Server: whois.ovh.com
   Referral URL: http://www.ovh.com
   Name Server: NS1.OUVATON.COOP
   Name Server: NS2.OUVATON.COOP
   Name Server: NS3.OUVATON.COOP
   Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
   Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Updated Date: 28-nov-2015
   Creation Date: 11-dec-2003
   Expiration Date: 11-dec-2018

**Domain: chantez.eu**
Registrant:
NOT DISCLOSED!
Visit www.eurid.eu for webbased whois.
Onsite(s):
NOT DISCLOSED!
Visit www.eurid.eu for webbased whois.
Technical:
Name: Klaba Octave
Organisation: OVH
Language: fr
Phone: +33.899701761
Fax: +33.320200958
Email: support@ovh.com

Il faudrait récupérer les accès d'administration OVH (ou la personne qui gère ces domaines), non ?

**Comment by aeschbacher** [comment]
Ca y est, on a tous les identifiants
 => closing
